# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 15:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0005_auto_20170505_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='BookContent'),
        ),
    ]
