# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0006_libros_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='BookContent')),
            ],
        ),
        migrations.RemoveField(
            model_name='libros',
            name='content',
        ),
        migrations.AddField(
            model_name='libros',
            name='capitulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booker.Capitulos'),
        ),
    ]
