# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0007_auto_20170508_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='capitulo',
        ),
        migrations.AddField(
            model_name='libros',
            name='capitulo',
            field=models.ManyToManyField(default='', to='booker.Capitulos'),
        ),
    ]
