# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0008_auto_20170508_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='capitulo',
        ),
        migrations.AddField(
            model_name='capitulos',
            name='libro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booker.Libros'),
        ),
    ]
