# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0009_auto_20170509_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='contenido',
            field=models.FileField(blank=True, default='', upload_to='booker/libros'),
        ),
    ]
