# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0010_auto_20170515_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='contenido',
            field=models.FileField(blank=True, default='', null=True, upload_to='booker/libros'),
        ),
    ]
