# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booker', '0012_auto_20170515_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
